FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base

workdir /app
EXPOSE 5160

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore Cine.Resenha.Api/Cine.Resenha.Api.csproj
RUN dotnet publish Cine.Resenha.Api/Cine.Resenha.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet","Cine.Resenha.Api.dll"]
