// <auto-generated />
using System;
using Cine.Resenha.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.Resenha.Persistence.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    [Migration("20250529210707_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Resenha.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WatchedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhoChose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverLink = "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/84/14/20028635.jpg",
                            Duration = 129,
                            Rating = 3.0m,
                            ReleaseYear = 2006,
                            Summary = "Elizabeth Bennet vive com sua mãe, pai e irmãs no campo, na Inglaterra. Por ser uma das filhas mais velhas, ela enfrenta uma crescente pressão de seus pais para se casar. Quando Elizabeth é apresentada ao belo e rico Darcy, faíscas voam. Embora haja uma química óbvia entre os dois, a natureza excessivamente reservada de Darcy ameaça a relação.",
                            Title = "Orgulho e Preconceito",
                            Watched = true,
                            WatchedDate = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoChose = "Izabella"
                        },
                        new
                        {
                            Id = 2,
                            CoverLink = "https://m.media-amazon.com/images/M/MV5BZDUyOGEwMGYtM2ViNi00MjY3LTk4YzktNWJmZmY2NGFiNTgzXkEyXkFqcGc@._V1_.jpg",
                            Duration = 90,
                            Rating = 4.5m,
                            ReleaseYear = 1986,
                            Summary = "His Motorbike, Her Island tells the story of Koh, a young biker who finds solace in his motorcycle after a breakup, and Miyo, a free-spirited girl on an island who becomes captivated by his bike. Their connection deepens, and Miyo develops a passion for motorcycles, leading to a bittersweet story of love, loss, and the transformative power of the open road",
                            Title = "His Motorbike Her Island",
                            Watched = true,
                            WatchedDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoChose = "Teteu"
                        },
                        new
                        {
                            Id = 3,
                            CoverLink = "https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_.jpg",
                            Duration = 117,
                            Rating = 5.0m,
                            ReleaseYear = 1982,
                            Summary = "No século 21, uma corporação desenvolve clones humanos para serem usados como escravos em colônias fora da Terra, identificados como replicantes. Em 2019, um ex-policial é acionado para caçar um grupo fugitivo vivendo disfarçado em Los Angeles.",
                            Title = "Bladerunner",
                            Watched = true,
                            WatchedDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhoChose = "Andre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
